name: hch CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  workflow_dispatch:

jobs:
  test:
    name: Test using ${{ matrix.backend }} backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [memory, sqlite]

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          catch2 \
          libsqlite3-dev \
          libreadline-dev \
          libyaml-cpp-dev \
          python3-pybind11 \
          libspdlog-dev \
          qt6-base-dev \
          g++ \
          sqlite3

    - name: test
      run: |
        make clean
        make BACKEND=${{ matrix.backend }} test test_py
